version: '3.8'
services:
  db:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./../database/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER}
      MYSQL_HOST: ${MYSQL_HOST}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
